# Generated by Django 5.2 on 2026-08-05 15:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('country', models.CharField(db_index=True, max_length=128)),
                ('country_iso', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 (US, MX, BR, ...)', max_length=2)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('source', models.CharField(default='ghs_ucdb', max_length=32)),
                ('source_id', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'geos_city',
                'indexes': [models.Index(fields=['country_iso', 'city'], name='geos_city_country_878350_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_id'), name='uniq_geos_city_source_id')],
            },
        ),
    ]
