# Generated by Django 5.2 on 2026-08-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='admin_level',
            field=models.PositiveSmallIntegerField(db_index=True, default=2, help_text='0 = país (ADM0), 2 = municipio/condado (ADM2).'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Nombre ADM2; vacío para filas ADM0 (país).', max_length=255),
        ),
        migrations.AlterField(
            model_name='city',
            name='source',
            field=models.CharField(default='geoboundaries', max_length=32),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['admin_level', 'country_iso'], name='geos_city_admin_l_14fd66_idx'),
        ),
    ]
