# Generated by Django 5.2 on 2026-08-08 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geos', '0003_city_region_admin_level_hierarchy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='city',
            new_name='geos_city_country_0652a3_idx',
            old_name='geos_city_country_5f1a2b_idx',
        ),
    ]
