# Generated by Django 5.2 on 2026-06-14 01:11

import apps.vendors.models
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='prefix_oui',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper(apps.vendors.models._RegexpReplace(django.db.models.functions.text.Upper('normalized_prefix'), models.Value('(.{2})(.{2})(.{2})'), models.Value('\\1:\\2:\\3'), output_field=models.CharField(max_length=8))), output_field=models.CharField(max_length=8)),
        ),
        migrations.AddIndex(
            model_name='vendors',
            index=models.Index(fields=['prefix_oui'], name='vendor_prefix_oui_idx'),
        ),
    ]
