# Generated by Django 5.2 on 2026-08-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geos", "0001_initial"),
        ("misc", "0002_auto_20260406_2325"),
    ]

    operations = [
        migrations.CreateModel(
            name="WardrivingMobileView",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("mcc", models.IntegerField()),
                ("mnc", models.IntegerField()),
                ("lac", models.IntegerField()),
                ("cell_id", models.IntegerField()),
                ("cell_type", models.CharField()),
                ("state", models.SmallIntegerField()),
                ("enodeb_id", models.BigIntegerField()),
                ("sector_id", models.SmallIntegerField()),
                ("pci", models.SmallIntegerField()),
                ("band", models.TextField()),
                ("earfcn", models.IntegerField()),
                ("dl_freq_mhz", models.DecimalField(decimal_places=1, max_digits=8)),
                ("ul_freq_mhz", models.DecimalField(decimal_places=1, max_digits=8)),
                ("rssi", models.IntegerField()),
                ("rsrp", models.IntegerField()),
                ("rsrq", models.IntegerField()),
                ("sinr", models.IntegerField()),
                ("signal_streng", models.CharField()),
                ("provider", models.TextField()),
                ("tech", models.TextField()),
                ("first_seen", models.DateTimeField()),
                ("device_source", models.CharField()),
                ("uploaded_by", models.TextField()),
                (
                    "current_latitude",
                    models.DecimalField(decimal_places=7, max_digits=13),
                ),
                (
                    "current_longitude",
                    models.DecimalField(decimal_places=7, max_digits=13),
                ),
                ("city", models.CharField()),
                ("country", models.CharField()),
                ("country_iso", models.CharField()),
            ],
            options={
                "db_table": "wardriving_mobile",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="wardrivingvendorview",
            name="city",
            field=models.CharField(),
        ),
        migrations.AddField(
            model_name="wardrivingvendorview",
            name="country",
            field=models.CharField(),
        ),
        migrations.AddField(
            model_name="wardrivingvendorview",
            name="country_iso",
            field=models.CharField(),
        ),
    ]
