# Generated by Django 5.2 on 2026-03-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wardriving", "0012_alter_ltewardriving_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="wardriving",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["uploaded_by", "mac", "channel"],
                name="wardriving_up_mac_ch_alv",
            ),
        ),
    ]
