# Generated by Django 5.2 on 2026-03-08 22:20

import django_db_views.migration_functions
import django_db_views.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardriving', '0012_alter_ltewardriving_options'),
    ]

    operations = [
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration("SELECT\n            wardriving.mac,\n            COALESCE(vendor.registry, 'Not setted yet') AS registry,\n            COALESCE(vendor.organization_name, 'Not found yet') AS vendor,\n            COALESCE(vendor.source, 'Not provided yet') AS source,\n            wardriving.ssid,\n            wardriving.auth_mode,\n            wardriving.first_seen,\n            wardriving.channel,\n            wardriving.rssi,\n            CASE\n                WHEN wardriving.rssi > -50 THEN 'Excellent'\n                WHEN wardriving.rssi BETWEEN -60 AND -50 THEN 'Good'\n                WHEN wardriving.rssi BETWEEN -70 AND -60 THEN 'Fair'\n                ELSE 'Weak'\n            END AS signal_streng,\n            wardriving.device_source,\n            wardriving.uploaded_by,\n            wardriving.type,\n            wardriving.current_latitude,\n            wardriving.current_longitude,\n            wardriving.altitude_meters,\n            wardriving.accuracy_meters\n        FROM wardriving\n        LEFT JOIN vendor ON UPPER(REGEXP_REPLACE(vendor.normalized_prefix,'(.{2})(.{2})(.{2})', '\\1:\\2:\\3'))=UPPER(SUBSTRING(wardriving.mac,1,8))\n        WHERE\n            (wardriving.current_latitude!=0 AND wardriving.current_longitude!=0)\n\t        AND wardriving.deleted_at is NULL", 'wardriving_vendor', engine='django.db.backends.postgresql'),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration('', 'wardriving_vendor', engine='django.db.backends.postgresql'),
            atomic=False,
        ),
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration('SELECT 1 AS id WHERE 1=0', 'wardriving_vendor', engine='django.db.backends.sqlite3'),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration('', 'wardriving_vendor', engine='django.db.backends.sqlite3'),
            atomic=False,
        ),
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration('SELECT 1 AS id WHERE 1=0', 'wardriving_vendor', engine='django.db.backends.mysql'),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration('', 'wardriving_vendor', engine='django.db.backends.mysql'),
            atomic=False,
        ),
    ]
