# Generated by Django 5.2 on 2026-04-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wardriving", "0014_auto_20260324_2331"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WardrivingVendorsView",
        ),
    ]
