# Generated by Django 5.2 on 2026-04-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardriving', '0016_alter_ltewardriving_device_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltewardriving',
            name='device_source',
            field=models.CharField(choices=[('unknown', 'unknown'), ('minino', 'minino'), ('flipper dev board', 'flipper dev board'), ('flipper dev board pro', 'flipper dev board pro'), ('marauder v4', 'marauder v4'), ('marauder v6', 'marauder v6'), ('flipper bffb', 'flipper bffb'), ('marauder esp32', 'marauder esp32'), ('rf custom firmware wifi', 'rf custom firmware wifi'), ('rf custom firmware lte', 'rf custom firmware lte'), ('kismet', 'kismet'), ('wardriver uk', 'wardriver uk'), ('kiisu board', 'kiisu board'), ('pwnterrey marauder', 'pwnterrey marauder'), ('wiggle mobile wifi', 'wiggle mobile wifi'), ('other', 'other')], default='unknown', max_length=50, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='wardriving',
            name='device_source',
            field=models.CharField(choices=[('unknown', 'unknown'), ('minino', 'minino'), ('flipper dev board', 'flipper dev board'), ('flipper dev board pro', 'flipper dev board pro'), ('marauder v4', 'marauder v4'), ('marauder v6', 'marauder v6'), ('flipper bffb', 'flipper bffb'), ('marauder esp32', 'marauder esp32'), ('rf custom firmware wifi', 'rf custom firmware wifi'), ('rf custom firmware lte', 'rf custom firmware lte'), ('kismet', 'kismet'), ('wardriver uk', 'wardriver uk'), ('kiisu board', 'kiisu board'), ('pwnterrey marauder', 'pwnterrey marauder'), ('wiggle mobile wifi', 'wiggle mobile wifi'), ('other', 'other')], default='unknown', max_length=50, verbose_name='Source'),
        ),
    ]
