# Generated by Django 5.2 on 2026-06-14 01:11

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardriving', '0018_alter_ltewardriving_device_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardriving',
            name='mac_oui',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper(django.db.models.functions.text.Substr('mac', 1, 8)), output_field=models.CharField(max_length=8)),
        ),
        migrations.AddIndex(
            model_name='ltewardriving',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['uploaded_by', '-first_seen'], name='lte_map_user_fs'),
        ),
        migrations.AddIndex(
            model_name='wardriving',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['uploaded_by', '-first_seen'], name='wardriving_map_user_fs'),
        ),
        migrations.AddIndex(
            model_name='wardriving',
            index=models.Index(fields=['mac_oui'], name='wardriving_mac_oui_idx'),
        ),
    ]
