# Generated by Django 5.2 on 2026-06-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardriving', '0019_wardriving_mac_oui_ltewardriving_lte_map_user_fs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltewardriving',
            name='cell_type',
            field=models.CharField(choices=[('serving', 'Serving'), ('neighbor', 'Neighbor')], default='serving', max_length=8, verbose_name='Cell Type'),
        ),
        migrations.AddField(
            model_name='ltewardriving',
            name='dl_freq_mhz',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='DL Frequency (MHz)'),
        ),
        migrations.AddField(
            model_name='ltewardriving',
            name='earfcn',
            field=models.IntegerField(default=0, help_text='E-UTRA Absolute Radio Frequency Channel Number.', verbose_name='EARFCN'),
        ),
        migrations.AddField(
            model_name='ltewardriving',
            name='enodeb_id',
            field=models.BigIntegerField(default=0, help_text='cell_id // 256', verbose_name='eNodeB ID'),
        ),
        migrations.AddField(
            model_name='ltewardriving',
            name='pci',
            field=models.SmallIntegerField(default=0, verbose_name='PCI (Physical Cell ID)'),
        ),
        migrations.AddField(
            model_name='ltewardriving',
            name='sector_id',
            field=models.SmallIntegerField(default=0, help_text='cell_id % 256', verbose_name='Sector ID'),
        ),
        migrations.AddField(
            model_name='ltewardriving',
            name='state',
            field=models.SmallIntegerField(default=0, help_text='1=home, 5=roaming, 0/2/3=not registered.', verbose_name='Registration State'),
        ),
        migrations.AddField(
            model_name='ltewardriving',
            name='ul_freq_mhz',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='UL Frequency (MHz)'),
        ),
        migrations.AlterField(
            model_name='ltewardriving',
            name='current_latitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=13, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='ltewardriving',
            name='current_longitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=13, verbose_name='Longitude'),
        ),
        migrations.AddIndex(
            model_name='ltewardriving',
            index=models.Index(fields=['cell_type'], name='lte_cell_type_idx'),
        ),
        migrations.AddIndex(
            model_name='ltewardriving',
            index=models.Index(fields=['pci'], name='lte_pci_idx'),
        ),
        migrations.AddIndex(
            model_name='ltewardriving',
            index=models.Index(fields=['earfcn'], name='lte_earfcn_idx'),
        ),
        migrations.AddIndex(
            model_name='ltewardriving',
            index=models.Index(fields=['enodeb_id'], name='lte_enodeb_idx'),
        ),
    ]
