# Generated by Django 5.2 on 2026-08-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardriving', '0023_backfill_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltewardriving',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City (denormalized)'),
        ),
        migrations.AddField(
            model_name='ltewardriving',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Country (denormalized)'),
        ),
        migrations.AddField(
            model_name='ltewardriving',
            name='country_iso',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='Country ISO (denormalized)'),
        ),
        migrations.AddField(
            model_name='wardriving',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City (denormalized)'),
        ),
        migrations.AddField(
            model_name='wardriving',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Country (denormalized)'),
        ),
        migrations.AddField(
            model_name='wardriving',
            name='country_iso',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='Country ISO (denormalized)'),
        ),
        migrations.AddIndex(
            model_name='ltewardriving',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['country_iso', 'city'], name='lte_country_city_alv'),
        ),
        migrations.AddIndex(
            model_name='wardriving',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['country_iso', 'city'], name='wardriving_country_city_alv'),
        ),
    ]
